import { District } from '../types/game';

export const DISTRICTS_DATA: District[] = [
  {
    id: 'midtown',
    name: 'Midtown Manhattan',
    borough: 'Manhattan',
    completion: 65,
    threat: 'Symbiote Surge',
    crimes: [
      {
        id: 'crime_midtown_symbiote_nest',
        title: 'Grand Central Symbiote Nest',
        districtId: 'midtown',
        type: 'symbiote_nest',
        description:
          'A massive alien symbiote hive has rooted outside Grand Central Terminal! Protect sonic purifiers and defeat Symbiote Behemoths.',
        threat: 'Severe',
        heroTokens: 3,
        techParts: 45,
        xpReward: 350,
        completed: false,
        gameMode: 'combat',
      },
      {
        id: 'crime_midtown_drone_chase',
        title: 'Kraven Talon Drone Pursuit',
        districtId: 'midtown',
        type: 'unidentified_target',
        description:
          'Hunter surveillance drones are scanning Manhattan rooftops! Deploy Web Wings to navigate skyscraper slipstreams and disable them.',
        threat: 'High',
        heroTokens: 2,
        techParts: 35,
        xpReward: 260,
        completed: false,
        gameMode: 'traversal',
      },
    ],
  },
  {
    id: 'financial_district',
    name: 'Financial District',
    borough: 'Manhattan',
    completion: 80,
    threat: 'Moderate',
    crimes: [
      {
        id: 'crime_fidi_hunter_base',
        title: "Kraven's Hunter Blind",
        districtId: 'financial_district',
        type: 'hunter_base',
        description:
          "Elite hunters have fortified an abandoned high-rise rooftop with laser tripwires and robotic hound turrets. Infiltrate and neutralize.",
        threat: 'High',
        heroTokens: 2,
        techParts: 40,
        xpReward: 300,
        completed: false,
        gameMode: 'combat',
      },
      {
        id: 'crime_fidi_speed_run',
        title: 'Wall Street Web-Wing Sprint',
        districtId: 'financial_district',
        type: 'unidentified_target',
        description:
          'Navigate tight building canyons at 90+ mph using wind tunnels and slingshot points across Lower Manhattan.',
        threat: 'Moderate',
        heroTokens: 1,
        techParts: 25,
        xpReward: 200,
        completed: true,
        gameMode: 'traversal',
      },
    ],
  },
  {
    id: 'central_park',
    name: 'Central Park',
    borough: 'Manhattan',
    completion: 45,
    threat: 'High',
    crimes: [
      {
        id: 'crime_park_symbiote_horde',
        title: 'Ramble Woods Symbiote Swarm',
        districtId: 'central_park',
        type: 'symbiote_nest',
        description:
          'Corrupted tendrils are strangling Central Park trees. Swarms of tendril lashers are ambushing civilians!',
        threat: 'Severe',
        heroTokens: 3,
        techParts: 50,
        xpReward: 380,
        completed: false,
        gameMode: 'combat',
      },
      {
        id: 'crime_park_sandman',
        title: "Marko's Lost Memory Crystal",
        districtId: 'central_park',
        type: 'marko_memory',
        description:
          'Locate and shatter Flint Marko’s crystallized sand memory to uncover his desperate message regarding his daughter Keemia.',
        threat: 'Moderate',
        heroTokens: 2,
        techParts: 30,
        xpReward: 220,
        completed: false,
        gameMode: 'combat',
      },
    ],
  },
  {
    id: 'astoria',
    name: 'Astoria & Queens',
    borough: 'Queens',
    completion: 50,
    threat: 'Moderate',
    crimes: [
      {
        id: 'crime_astoria_car_chase',
        title: 'Armored Truck Hijacking',
        districtId: 'astoria',
        type: 'car_chase',
        description:
          'Heavily armed mercenaries are speeding down the Grand Central Parkway. Swing in pursuit, dodge rocket fire, and web their axles!',
        threat: 'Moderate',
        heroTokens: 2,
        techParts: 30,
        xpReward: 240,
        completed: false,
        gameMode: 'traversal',
      },
      {
        id: 'crime_astoria_prowler',
        title: 'Prowler High-Tech Cache',
        districtId: 'astoria',
        type: 'unidentified_target',
        description:
          'Uncle Aaron hid an advanced stealth audio transmitter on a Queens water tower. Align the sound waves to unlock the vault.',
        threat: 'Low',
        heroTokens: 1,
        techParts: 30,
        xpReward: 180,
        completed: true,
        gameMode: 'traversal',
      },
    ],
  },
  {
    id: 'williamsburg',
    name: 'Williamsburg & Brooklyn',
    borough: 'Brooklyn',
    completion: 75,
    threat: 'High',
    crimes: [
      {
        id: 'crime_brooklyn_bridge_clash',
        title: 'Brooklyn Bridge Hunter Ambush',
        districtId: 'williamsburg',
        type: 'hunter_base',
        description:
          'Kraven’s big-game hunters have trapped a commuter convoy on the Brooklyn Bridge cables. Clear the bridge deck before reinforcements arrive.',
        threat: 'High',
        heroTokens: 3,
        techParts: 45,
        xpReward: 320,
        completed: false,
        gameMode: 'combat',
      },
      {
        id: 'crime_coney_speed_rush',
        title: 'East River Web-Wings Super-Tunnel',
        districtId: 'williamsburg',
        type: 'unidentified_target',
        description:
          'Soar across the East River under suspension bridge arches using supersonic air currents and web-line slingshots.',
        threat: 'Moderate',
        heroTokens: 2,
        techParts: 35,
        xpReward: 250,
        completed: false,
        gameMode: 'traversal',
      },
    ],
  },
  {
    id: 'harlem',
    name: 'Harlem',
    borough: 'Manhattan',
    completion: 90,
    threat: 'Clean',
    crimes: [
      {
        id: 'crime_harlem_rooftop_defense',
        title: 'Community Center Defense',
        districtId: 'harlem',
        type: 'hunter_base',
        description:
          'Defend Miles’ neighborhood community garden against rogue mercenaries seeking advanced solar energy cells.',
        threat: 'Moderate',
        heroTokens: 2,
        techParts: 35,
        xpReward: 280,
        completed: true,
        gameMode: 'combat',
      },
      {
        id: 'crime_harlem_music_wings',
        title: 'Harlem Rooftops Flight Rhythm',
        districtId: 'harlem',
        type: 'unidentified_target',
        description:
          'Glide across Harlem’s vibrant brownstone avenue rooftops following Miles’ custom soundtrack audio beacons.',
        threat: 'Low',
        heroTokens: 1,
        techParts: 25,
        xpReward: 190,
        completed: true,
        gameMode: 'traversal',
      },
    ],
  },
];
