import { SpiderBot } from '../types/game';

export const SPIDER_BOTS_DATA: SpiderBot[] = [
  {
    id: 'bot_2099',
    name: 'Spider-Man 2099 Bot',
    universe: 'Earth-928',
    rarity: 'Legendary',
    district: 'Financial District',
    primaryColor: '#0284C7',
    secondaryColor: '#EF4444',
    quote: '"Shock you! The timeline must not collapse under temporal anomalies."',
    collected: true,
  },
  {
    id: 'bot_spider_gwen',
    name: 'Ghost-Spider Bot',
    universe: 'Earth-65',
    rarity: 'Legendary',
    district: 'Midtown Manhattan',
    primaryColor: '#F43F5E',
    secondaryColor: '#38BDF8',
    quote: '"Where I come from, rhythm is everything. Keep the beat going!"',
    collected: true,
  },
  {
    id: 'bot_superior',
    name: 'Superior Spider-Man Bot',
    universe: 'Earth-616',
    rarity: 'Rare',
    district: 'Central Park',
    primaryColor: '#DC2626',
    secondaryColor: '#09090B',
    quote: '"The die is cast! Only scientific perfection can safeguard this metropolis."',
    collected: false,
  },
  {
    id: 'bot_noir',
    name: 'Spider-Man Noir Bot',
    universe: 'Earth-90214',
    rarity: 'Rare',
    district: 'Williamsburg & Brooklyn',
    primaryColor: '#3F3F46',
    secondaryColor: '#71717A',
    quote: '"Wherever I go, the wind follows. And the wind smells like rain... and cheap cigars."',
    collected: false,
  },
  {
    id: 'bot_spider_punk',
    name: 'Spider-Punk Bot',
    universe: 'Earth-138',
    rarity: 'Legendary',
    district: 'Astoria & Queens',
    primaryColor: '#EF4444',
    secondaryColor: '#3B82F6',
    quote: '"I do not believe in consistency, corporate authority, or fascistic algorithms."',
    collected: true,
  },
  {
    id: 'bot_scarlet_spider',
    name: 'Scarlet Spider Bot',
    universe: 'Earth-616',
    rarity: 'Common',
    district: 'Harlem',
    primaryColor: '#E11D48',
    secondaryColor: '#2563EB',
    quote: '"Ben Reilly here. Denim sleeveless hoodie is high fashion, no matter what they say."',
    collected: false,
  },
  {
    id: 'bot_sp_dr',
    name: 'SP//dr Peni Parker Bot',
    universe: 'Earth-14512',
    rarity: 'Rare',
    district: 'Financial District',
    primaryColor: '#E11D48',
    secondaryColor: '#F59E0B',
    quote: '"Biochemical psychic link synced at 99.4%! All systems nominal, Parker."',
    collected: false,
  },
  {
    id: 'bot_iron_spider',
    name: 'Iron Spider Bot',
    universe: 'Earth-616',
    rarity: 'Rare',
    district: 'Midtown Manhattan',
    primaryColor: '#DC2626',
    secondaryColor: '#F59E0B',
    quote: '"Stark Industries nanotech firmware update applied: extra waldoes deployed."',
    collected: false,
  },
  {
    id: 'bot_spider_ham',
    name: 'Spider-Ham Bot',
    universe: 'Earth-8311',
    rarity: 'Legendary',
    district: 'Central Park',
    primaryColor: '#FB7185',
    secondaryColor: '#1E3A8A',
    quote: '"That does not hurt, because it is cartoon physics! Have a giant wooden mallet!"',
    collected: false,
  },
  {
    id: 'bot_spider_knight',
    name: 'Spider-Knight Bot',
    universe: 'Earth-TRN978',
    rarity: 'Common',
    district: 'Astoria & Queens',
    primaryColor: '#94A3B8',
    secondaryColor: '#DC2626',
    quote: '"By the sacred honor of the Round Table of York, evil shall yield to my blade!"',
    collected: false,
  },
];
