import { Suit } from '../types/game';

export const SUITS_DATA: Suit[] = [
  // --- PETER PARKER SUITS ---
  {
    id: 'peter_advanced_2',
    hero: 'peter',
    name: 'Advanced Suit 2.0',
    subtitle: 'Insomniac Flagship Red & Blue',
    description:
      "Peter's updated suit tailored for Marvel's Spider-Man 2. Features flexible carbon-mesh red fabric, reinforced navy, and the signature white spider emblem.",
    unlocked: true,
    techCost: 0,
    tokenCost: 0,
    colors: {
      primary: '#E52521',
      secondary: '#1A365D',
      glow: '#FFFFFF',
      webColor: '#FFFFFF',
      accent: '#FFFFFF',
    },
    stats: {
      traversal: 85,
      damage: 80,
      defense: 80,
      focusRate: 85,
    },
    specialPerk: 'Web Overdrive: Web-Shooters reload 50% faster.',
    perkIcon: 'flash',
  },
  {
    id: 'peter_symbiote_black',
    hero: 'peter',
    name: 'Black Symbiote Suit',
    subtitle: 'The Alien Organism',
    description:
      'Bonded with the alien symbiote. Unleashes devastating tendril strikes, savage brute force, and an uncontrollable surge of raw fury.',
    unlocked: false,
    techCost: 60,
    tokenCost: 4,
    colors: {
      primary: '#0B0B12',
      secondary: '#2E1065',
      glow: '#A855F7',
      webColor: '#1F1F2E',
      accent: '#9333EA',
    },
    stats: {
      traversal: 90,
      damage: 98,
      defense: 88,
      focusRate: 92,
    },
    specialPerk: 'Symbiote Surge: Tendril attacks deal +60% damage and stagger elite brutes.',
    perkIcon: 'skull',
  },
  {
    id: 'peter_anti_venom',
    hero: 'peter',
    name: 'Anti-Venom Suit',
    subtitle: 'The Cleansing Light',
    description:
      'Forged from Martin Li’s inner light and residual symbiote remnants. Possesses the power to cleanse symbiote corruption across New York City.',
    unlocked: false,
    techCost: 90,
    tokenCost: 6,
    colors: {
      primary: '#F8FAFC',
      secondary: '#0F172A',
      glow: '#38BDF8',
      webColor: '#E2E8F0',
      accent: '#0EA5E9',
    },
    stats: {
      traversal: 92,
      damage: 95,
      defense: 94,
      focusRate: 96,
    },
    specialPerk: 'Cleansing Light: Deals +50% damage against Symbiote nests and heals 25 HP per finisher.',
    perkIcon: 'shield-checkmark',
  },
  {
    id: 'peter_superior',
    hero: 'peter',
    name: 'Superior Spider-Man',
    subtitle: 'Otto Octavius Design',
    description:
      'Bold crimson and carbon-black suit engineered with ruthless tactical efficiency, armed with four retractable spider waldoes.',
    unlocked: false,
    techCost: 45,
    tokenCost: 3,
    colors: {
      primary: '#DC2626',
      secondary: '#111827',
      glow: '#EF4444',
      webColor: '#475569',
      accent: '#F87171',
    },
    stats: {
      traversal: 84,
      damage: 88,
      defense: 78,
      focusRate: 88,
    },
    specialPerk: 'Superior Protocol: Critical hits trigger nanotech shockwave that hits 2 extra targets.',
    perkIcon: 'hardware-chip',
  },
  {
    id: 'peter_raimi_webbed',
    hero: 'peter',
    name: 'Webbed Suit',
    subtitle: 'Classic Silver Raised Webbing',
    description:
      'The legendary suit featuring iconic raised metallic silver webbing and distinct angular lenses. A timeless classic of cinematic history.',
    unlocked: false,
    techCost: 40,
    tokenCost: 2,
    colors: {
      primary: '#B91C1C',
      secondary: '#1E3A8A',
      glow: '#CBD5E1',
      webColor: '#E2E8F0',
      accent: '#E2E8F0',
    },
    stats: {
      traversal: 82,
      damage: 82,
      defense: 86,
      focusRate: 80,
    },
    specialPerk: "Hero's Resolve: Spider-Sense parry timing window is 30% more generous.",
    perkIcon: 'eye',
  },
  {
    id: 'peter_iron_spider',
    hero: 'peter',
    name: 'Iron Spider Armor',
    subtitle: 'Stark Nanotech Armor',
    description:
      'Crafted with nanotech liquid-metal alloys. Equipped with golden mechanical appendages and high-caliber laser deflector shields.',
    unlocked: false,
    techCost: 75,
    tokenCost: 5,
    colors: {
      primary: '#991B1B',
      secondary: '#B45309',
      glow: '#FBBF24',
      webColor: '#F59E0B',
      accent: '#FDE047',
    },
    stats: {
      traversal: 86,
      damage: 90,
      defense: 96,
      focusRate: 84,
    },
    specialPerk: 'Nanite Shield: Deflects Kraven Hunter laser fire back at attackers.',
    perkIcon: 'shield',
  },

  // --- MILES MORALES SUITS ---
  {
    id: 'miles_upgraded',
    hero: 'miles',
    name: 'Upgraded Classic Suit',
    subtitle: 'Harlem Champion',
    description:
      "Miles' signature matte black bodysuit with vibrant crimson web stripes and high-conductivity venom channels.",
    unlocked: true,
    techCost: 0,
    tokenCost: 0,
    colors: {
      primary: '#18181B',
      secondary: '#DC2626',
      glow: '#F59E0B',
      webColor: '#EF4444',
      accent: '#F59E0B',
    },
    stats: {
      traversal: 88,
      damage: 82,
      defense: 78,
      focusRate: 90,
    },
    specialPerk: 'Venom Infusion: Bio-electric Venom bar charges 40% faster on melee combos.',
    perkIcon: 'flash',
  },
  {
    id: 'miles_2099',
    hero: 'miles',
    name: 'Miles 2099 Suit',
    subtitle: 'Nueva York Cyberpunk',
    description:
      'Futuristic chassis fitted with glowing cyan conduits, digital optics, and holographic web-wing aerodynamic foils.',
    unlocked: false,
    techCost: 50,
    tokenCost: 3,
    colors: {
      primary: '#0F172A',
      secondary: '#06B6D4',
      glow: '#22D3EE',
      webColor: '#38BDF8',
      accent: '#67E8F9',
    },
    stats: {
      traversal: 96,
      damage: 85,
      defense: 80,
      focusRate: 86,
    },
    specialPerk: 'Cyber Glider: Web-Wings glide speed +40% with zero stamina drop in wind tunnels.',
    perkIcon: 'airplane',
  },
  {
    id: 'miles_bodega_cat',
    hero: 'miles',
    name: 'Bodega Cat Suit',
    subtitle: 'With Spider-Cat Partner!',
    description:
      'Comfy gray hoodie and backpack carrying "Spider-Cat", the masked bodega feline who leaps out to assist with ferocious claw finishers!',
    unlocked: false,
    techCost: 65,
    tokenCost: 4,
    colors: {
      primary: '#F97316',
      secondary: '#475569',
      glow: '#FDBA74',
      webColor: '#FB923C',
      accent: '#FED7AA',
    },
    stats: {
      traversal: 84,
      damage: 88,
      defense: 84,
      focusRate: 94,
    },
    specialPerk: 'Feline Finisher: Spider-Cat attacks during finishers, dropping extra Tech Parts.',
    perkIcon: 'paw',
  },
  {
    id: 'miles_the_end',
    hero: 'miles',
    name: 'The End Suit',
    subtitle: 'Post-Apocalyptic Survivor',
    description:
      'Hardened camo combat vest, high-top sneakers, and crimson web arm-wraps designed to defend a futuristic Harlem.',
    unlocked: false,
    techCost: 45,
    tokenCost: 3,
    colors: {
      primary: '#3F3F46',
      secondary: '#B91C1C',
      glow: '#F87171',
      webColor: '#DC2626',
      accent: '#FCA5A5',
    },
    stats: {
      traversal: 90,
      damage: 86,
      defense: 85,
      focusRate: 82,
    },
    specialPerk: 'Street Grit: Slingshot launches travel 50% further with explosive takeoff shockwave.',
    perkIcon: 'speedometer',
  },
  {
    id: 'miles_10th_anniversary',
    hero: 'miles',
    name: '10th Anniversary Suit',
    subtitle: 'Celebration of Miles',
    description:
      'Sleek stylized dark armor accented by glowing magenta bioluminescence and high-voltage blue capacitors.',
    unlocked: false,
    techCost: 75,
    tokenCost: 5,
    colors: {
      primary: '#172554',
      secondary: '#E11D48',
      glow: '#38BDF8',
      webColor: '#F43F5E',
      accent: '#60A5FA',
    },
    stats: {
      traversal: 91,
      damage: 92,
      defense: 88,
      focusRate: 92,
    },
    specialPerk: 'Mega Venom Shock: Mega Venom Blast radius is 50% larger and stuns all nearby enemies.',
    perkIcon: 'thunderstorm',
  },
  {
    id: 'miles_strike',
    hero: 'miles',
    name: 'S.T.R.I.K.E. Suit',
    subtitle: 'Tactical Exoskeleton',
    description:
      'Militarized combat armor featuring reinforced titanium plating, amber optics, and bio-electric gauntlets.',
    unlocked: false,
    techCost: 60,
    tokenCost: 4,
    colors: {
      primary: '#1E293B',
      secondary: '#D97706',
      glow: '#F59E0B',
      webColor: '#FBBF24',
      accent: '#FDE68A',
    },
    stats: {
      traversal: 85,
      damage: 94,
      defense: 95,
      focusRate: 80,
    },
    specialPerk: 'Kinetic Impact: Heavy strike hits emit a seismic shockwave that stuns shielded enemies.',
    perkIcon: 'fitness',
  },
];
