import { TechUpgrade } from '../types/game';

export const TECH_UPGRADES_DATA: TechUpgrade[] = [
  // --- TRAVERSAL ---
  {
    id: 'traversal_web_wings',
    category: 'traversal',
    title: 'Web-Wings Aerodynamics',
    description: 'Upgrades underarm webbing glide surface for higher aerodynamic lift and wind tunnel speed.',
    level: 1,
    maxLevel: 4,
    costTech: [20, 40, 70, 100],
    costTokens: [1, 2, 3, 5],
    statBoost: '+15% Glide Velocity & +25% Wind Tunnel Acceleration',
  },
  {
    id: 'traversal_slingshot',
    category: 'traversal',
    title: 'Supercharged Slingshot',
    description: 'Reinforces dual web anchors for supersonic initial launch across NYC skyscrapers.',
    level: 1,
    maxLevel: 3,
    costTech: [25, 50, 80],
    costTokens: [1, 2, 4],
    statBoost: '+30% Slingshot Launch Distance & Speed Boost',
  },
  {
    id: 'traversal_point_launch',
    category: 'traversal',
    title: 'Point Launch Boost',
    description: 'Timing a web-zip release off building spires launches Spidey with maximum forward kinetic energy.',
    level: 1,
    maxLevel: 3,
    costTech: [15, 35, 60],
    costTokens: [1, 2, 3],
    statBoost: '+20% Web-Zip Launch Height & Speed',
  },

  // --- DAMAGE ---
  {
    id: 'damage_kinetic_strike',
    category: 'damage',
    title: 'Kinetic Melee Enhancer',
    description: 'Nanotech micro-servos amplify strike power in Peter and Miles melee combo chains.',
    level: 1,
    maxLevel: 4,
    costTech: [20, 45, 75, 110],
    costTokens: [1, 2, 4, 6],
    statBoost: '+20% Melee Strike Damage per level',
  },
  {
    id: 'damage_web_viscosity',
    category: 'damage',
    title: 'Tensile Web Fluid',
    description: 'Higher molecular weight polymer rapidly immobilizes Hunters and Symbiote tendrils in fewer shots.',
    level: 1,
    maxLevel: 3,
    costTech: [25, 50, 85],
    costTokens: [1, 3, 5],
    statBoost: 'Web-Shooters pin enemies in 2 hits instead of 3',
  },
  {
    id: 'damage_aerial_combat',
    category: 'damage',
    title: 'Aerial Dominance',
    description: 'Air combos and air-launches deal devastating bonus damage with extended hangtime.',
    level: 1,
    maxLevel: 3,
    costTech: [30, 60, 95],
    costTokens: [2, 3, 5],
    statBoost: '+35% Aerial Combo Critical Hit Damage',
  },

  // --- HEALTH ---
  {
    id: 'health_ballistic_weave',
    category: 'health',
    title: 'Carbon-Fiber Weave',
    description: 'Fortifies suit lining with impact-absorbing graphene to withstand brute force blows.',
    level: 1,
    maxLevel: 4,
    costTech: [20, 40, 65, 95],
    costTokens: [1, 2, 3, 4],
    statBoost: '+25 Max Health Points per tier',
  },
  {
    id: 'health_cellular_regen',
    category: 'health',
    title: 'Cellular Regeneration',
    description: 'Harnesses symbiote & bio-electric biological factors to passively mend tissue in combat.',
    level: 0,
    maxLevel: 3,
    costTech: [35, 65, 100],
    costTokens: [2, 4, 6],
    statBoost: 'Passive Health Recovery: 6 HP per 4 seconds in combat',
  },

  // --- FOCUS & ULTIMATES ---
  {
    id: 'focus_flow_generator',
    category: 'focus',
    title: 'Focus Capacitor',
    description: 'Dynamic bio-energy feedback loops fill Focus meters much faster on successful dodges and parries.',
    level: 1,
    maxLevel: 4,
    costTech: [25, 50, 80, 120],
    costTokens: [1, 3, 4, 6],
    statBoost: '+25% Focus Generation on Perfect Parries',
  },
  {
    id: 'focus_ultimate_overdrive',
    category: 'focus',
    title: 'Surge & Venom Overdrive',
    description: "Maximizes the destructive output of Peter's Symbiote Surge and Miles' Mega Venom Blast.",
    level: 1,
    maxLevel: 3,
    costTech: [40, 80, 130],
    costTokens: [2, 5, 8],
    statBoost: '+40% Ultimate AoE Blast Damage & Duration',
  },
];
